#!/bin/bash

TMP_DIR="${TMPDIR}"
BASENAME="$(basename $0)"

test -z "${TMP_DIR}" && TMP_DIR="."
TMP_FILE="${TMP_DIR}/tmp-${BASENAME}-$$"

timeout 30 cif2cif "$@" > /dev/null 2>${TMP_FILE}

if [ "$?" == 124 ]
then
    echo --
else
    if grep -q 'ciftbx error:' ${TMP_FILE}
    then
        echo ERROR
    else
        if grep -q 'ciftbx warning:' ${TMP_FILE}
        then
            echo WARNING
        fi
    fi
fi

rm "${TMP_FILE}"
