#!/bin/bash

TMP_DIR="${TMPDIR}"
BASENAME="$(basename $0)"

test -z "${TMP_DIR}" && TMP_DIR="."
TMP_FILE="${TMP_DIR}/tmp-${BASENAME}-$$"

cif_linguist "$@" 2> ${TMP_FILE} >/dev/null

if grep -q 'CIF error' ${TMP_FILE}
then
    echo ERROR
fi

rm "${TMP_FILE}"
