#!/bin/bash

groovy -cp /usr/share/java/ciftools-java.jar -e '
import java.nio.file.Paths;
import org.rcsb.cif.CifIO;
import org.rcsb.cif.ParsingException;

try {
    CifIO.readFromPath( Paths.get( args[0] ) )
} catch (ParsingException) {
    println "ERROR"
}' $1
