#!/bin/bash

java -cp /usr/local/share/maven-repo/org/xml-cml/cifxom/debian/cifxom-debian.jar:/usr/share/java/xom.jar:/usr/share/java/jaxen.jar:/usr/share/java/log4j-1.2.jar:/usr/share/java/commons-io.jar org.xmlcml.cif.CIF -CIFIN "$@" >/dev/null 2>&1 || echo ERROR
