#!/bin/bash

TMP_DIR="${TMPDIR}"
BASENAME="$(basename $0)"

test -z "${TMP_DIR}" && TMP_DIR="."
TMP_FILE="${TMP_DIR}/tmp-${BASENAME}-$$"

export PYTHONPATH=${HOME}/src/startools-0.2.0/python/src

python \
    ${HOME}/src/startools-0.2.0/python/example-src/com/globalphasing/startools/star_example.py "$@" > ${TMP_FILE} 2>&1

if grep -q '^Summary of token types' ${TMP_FILE}
then
    OK=0
    if grep -q '0 BAD_CONSTRUCT' ${TMP_FILE}
    then
        if grep -q '0 SQUARE_BRACKET' ${TMP_FILE}
        then
            if grep -q '0 BAD_TOKEN' ${TMP_FILE}
            then
                OK=1
            fi
        fi
    fi
    if [ "${OK}" == 0 ]
    then
        echo WARNING
    fi
else
    echo ERROR
fi

rm "${TMP_FILE}"
