#!/bin/bash

TMP_DIR="${TMPDIR}"
BASENAME="$(basename $0)"

test -z "${TMP_DIR}" && TMP_DIR="."
TMP_FILE="${TMP_DIR}/tmp-${BASENAME}-$$"

cif2cbf "$@" 2>${TMP_FILE} >/dev/null

if grep -qP '^CBFlib (fatal )?error' ${TMP_FILE}
then
    echo ERROR
else
    grep -q '^CBFlib: warning' ${TMP_FILE} && echo WARNING
fi

rm "${TMP_FILE}"
