#!/bin/bash

TMP_DIR="${TMPDIR}"
BASENAME="$(basename $0)"

test -z "${TMP_DIR}" && TMP_DIR="."
TMP_FILE="${TMP_DIR}/tmp-${BASENAME}-$$"

timeout 30 cifZinc "$@" > ${TMP_FILE} 2>&1

if [ "$?" == 124 ]
then
    echo --
else
    if grep -q '^syntax error:' ${TMP_FILE}
    then
        echo ERROR
    fi
fi

rm "${TMP_FILE}"
